name: Build_Battle
version: '1.0-SNAPSHOT'
main: snowsan0113.build_battle.BuildBattle
api-version: '1.20'

commands:
  buildbattle_start:
    description: gameを開始するコマンド
    permission: buildbattle.commands.start
